version: '3.8'
services:
  oap:
    image: apache/skywalking-oap-server:9.3.0
    container_name: skywalking-oap
    ports:
      - "11800:11800"
      - "12800:12800"
    healthcheck:
      test: [ "CMD-SHELL", "/skywalking/bin/swctl ch" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    environment:
      SW_HEALTH_CHECKER: default
      JAVA_OPTS: "-Xms256m -Xmx256m"

  ui:
    image: apache/skywalking-ui:9.3.0
    container_name: skywalking-ui
    depends_on:
      oap:
        condition: service_healthy
    links:
      - oap
    ports:
      - "8081:8080"
    environment:
      SW_OAP_ADDRESS: http://oap:12800